# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0005_auto_20160221_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnizor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255, verbose_name='Nume')),
                ('descriere', models.TextField(blank=True, null=True, verbose_name='Descriere')),
                ('telefon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='ModPlata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50, verbose_name='Mod plata')),
            ],
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=255, verbose_name='Nume')),
                ('descriere', models.TextField(blank=True, null=True, verbose_name='Descriere')),
                ('telefon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='TermenPlata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=50, verbose_name='Tip termen')),
            ],
        ),
    ]
