# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0006_furnizor_modplata_producator_termenplata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcomanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_curent', models.IntegerField()),
                ('text', models.CharField(max_length=10)),
                ('persoana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Persoana')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Status')),
            ],
        ),
    ]
