# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0007_subcomanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomanda',
            name='persoana',
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='producator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Producator'),
        ),
    ]
