# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0008_auto_20160221_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomanda',
            name='cod_reper',
            field=models.CharField(max_length=100, null=True, verbose_name='Cod reper'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='furnizor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Furnizor'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='reper',
            field=models.TextField(null=True, verbose_name='Reper'),
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Status'),
        ),
    ]
