# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0009_auto_20160221_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomanda',
            name='cantitate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, null=True, verbose_name='Cantitate'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='data_livrare',
            field=models.DateTimeField(null=True, verbose_name='Data livrare'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='data_primire',
            field=models.DateTimeField(null=True, verbose_name='Data primire'),
        ),
    ]
