# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0010_auto_20160221_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomanda',
            name='data_primire',
            field=models.DateField(null=True, verbose_name='Data primire'),
        ),
    ]
