# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0012_auto_20160221_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomanda',
            name='intarziere',
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='pret',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True, verbose_name='Pret'),
        ),
    ]
