# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0013_auto_20160221_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomanda',
            name='data_de_facturare',
            field=models.DateField(null=True, verbose_name='Data de facturare'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='de_facturat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True, verbose_name='De facturat'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='facturat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True, verbose_name='Facturat'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='mod_plata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.ModPlata'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='termen_plata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.TermenPlata'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='tva_de_facturat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True, verbose_name='TVA de Facturat'),
        ),
        migrations.AddField(
            model_name='subcomanda',
            name='tva_facturat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True, verbose_name='TVA Facturat'),
        ),
    ]
