# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0014_auto_20160221_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomanda',
            name='text',
        ),
    ]
