# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0015_remove_subcomanda_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reper', models.CharField(max_length=100, null=True, verbose_name='Cod reper')),
                ('reper', models.TextField(null=True, verbose_name='Reper')),
            ],
        ),
        migrations.RemoveField(
            model_name='subcomanda',
            name='cod_reper',
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='data_primire',
            field=models.DateField(blank=True, null=True, verbose_name='Data primire'),
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='reper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Reper'),
        ),
    ]
