# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0016_auto_20160221_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomanda',
            name='de_facturat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='De facturat'),
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='facturat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='Facturat'),
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='tva_de_facturat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='TVA de Facturat'),
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='tva_facturat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='TVA Facturat'),
        ),
    ]
