# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderhelper', '0018_auto_20160221_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_unic', models.IntegerField()),
                ('data', models.DateField(verbose_name='Data')),
                ('obiect_succint', models.TextField(null=True, verbose_name='Obiect Succint')),
                ('data_livrare', models.DateField(null=True, verbose_name='Data livrare')),
                ('data_primire', models.DateField(blank=True, null=True, verbose_name='Data primire')),
                ('facturat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='Facturat')),
                ('de_facturat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='De facturat')),
                ('tva_facturat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='TVA Facturat')),
                ('tva_de_facturat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True, verbose_name='TVA de Facturat')),
                ('preluat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Preluare')),
                ('proiect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Proiect')),
                ('solicitant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Persoana', verbose_name='Solicitant')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orderhelper.Status')),
                ('subcomenzi', models.ManyToManyField(to='orderhelper.Subcomanda')),
            ],
        ),
    ]
