# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0023_auto_20160222_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 22, 19, 51, 10, 690327, tzinfo=utc), verbose_name='Data'),
        ),
    ]
