# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('orderhelper', '0026_auto_20160222_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='group',
            field=models.ManyToManyField(related_name='coamandas', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 24, 17, 51, 35, 95640, tzinfo=utc), verbose_name='Data'),
        ),
    ]
