# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0030_auto_20160227_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 27, 9, 7, 0, 341007, tzinfo=utc), verbose_name='Data'),
        ),
    ]
