# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0031_auto_20160227_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 27, 17, 24, 35, 94100, tzinfo=utc), verbose_name='Data'),
        ),
    ]
