# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0032_auto_20160227_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomanda',
            name='link',
        ),
        migrations.AddField(
            model_name='reper',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 28, 18, 22, 29, 955558, tzinfo=utc), verbose_name='Data'),
        ),
    ]
