# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0033_auto_20160228_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='data_livrare',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='de_facturat',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='tva_de_facturat',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='tva_facturat',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 28, 18, 40, 30, 42757, tzinfo=utc), verbose_name='Data'),
        ),
    ]
