# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 18:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0034_auto_20160228_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomanda',
            name='data_de_facturare',
        ),
        migrations.RemoveField(
            model_name='subcomanda',
            name='de_facturat',
        ),
        migrations.RemoveField(
            model_name='subcomanda',
            name='facturat',
        ),
        migrations.RemoveField(
            model_name='subcomanda',
            name='tva_de_facturat',
        ),
        migrations.RemoveField(
            model_name='subcomanda',
            name='tva_facturat',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 28, 18, 50, 41, 576498, tzinfo=utc), verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='subcomanda',
            name='pret',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Pret'),
        ),
    ]
