# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderhelper', '0035_auto_20160228_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='facturat',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 2, 28, 19, 19, 30, 886506, tzinfo=utc), verbose_name='Data'),
        ),
    ]
