language: python
python:
  - "2.7"
  - "3.2"


env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2

# command to install dependencies  
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install .--use-mirrors
  - pip install -r requirements.txt

  
# command to run tests
script: nosetests

notifications:
  email:
    recipients:
      - eduard.erja@gmail.com
      - eduard.erja@cerner.com
    on_success: always
    on_failure: always